import Layout from '../components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePicture from '../../public/images/profile/developer-pic-new.png';
//import profilePicture from '../../public/images/profile/developer-pic-new';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import AnimatedText from '../components/AnimatedText';
import Link from 'next/link';
//import { LinkArrow } from '../components/Icons';
import HireMe from '../components/HireMe';
import TransitionEffect from '../components/TransitionEffect';

const LinkArrow = ({ className, ...rest }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    viewBox="0 0 24 24"
    className={`w-full h-auto ${className}`}
    {...rest}
  >
    <path fill="none" d="M0 0h24v24H0z" />
    <path
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M11 7H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-5m-7 1L20 4m-5 0h5v5"
    />
  </svg>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center xs:block  text-dark w-full min-h-screen xs:min-h-[calc(100vh-244px)] dark:text-light xs:pt-[16%]">
        <Layout className="pt-24 md:pt-16 xs:pt-8">
          <div className="flex items-center justify-around lg:justify-center w-full">
            <div className="w-[32%] 2xl:w-[34%] xl:w-[36%] lg:w-0">
              <Image
                src={profilePicture}
                alt="profile picture"
                className="w-full h-auto lg:hidden lg:w-0"
                priority="true"
                sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-[80%] md:w-[90%] sm:w-full lg:text-center xs:gap-1">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-xl font-medium md:text-sm sm:text-xs">
                As a passionate full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects, showcasing my expertise in React.js and web
                development.
              </p>
              <div className="flex justify-between w-[90%] self-start lg:self-center mt-3">
                <div className="flex lg:justify-center lg:w-full lg:mt-0 items-start mt-4 ">
                  <div className="flex items-center">
                    <Link
                      href="/CV_Matthias_Floimayr.pdf"
                      target="_blank"
                      className="flex items-center bg-dark dark:bg-light text-light dark:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark hover:dark:text-light  hover:dark:bg-dark hover:dark:border-light border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                      download={true}
                    >
                      Resume
                      <LinkArrow className={'w-6 ml-1'} />
                    </Link>
                    <Link
                      href="mailto:matthiasfloimayr@gmail.com"
                      target="_blank"
                      className="ml-4 text-lg font-medium capitalize text-dark dark:text-light underline"
                    >
                      Contact
                    </Link>
                  </div>
                </div>
                <div className="flex justify-end">
                  <div className="inline-block w-24 2xl:w-20 xl:w-16 lg:hidden">
                    <Image
                      src={lightBulb}
                      alt="a lightbulb"
                      className="w-full h-auto"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
